[tool.poetry]
name = "blog"
version = "0.0.0"
description = "Daniel Himmelstein's Blog"
authors = ["Daniel Himmelstein"]

# https://python-poetry.org/docs/versions/
[tool.poetry.dependencies]
python = "^3.8"
pelican = "^4.2.0"
markdown = "^3.2.2"
smartypants = "^2.0.1"
jinja2 = "^2.11.2"
typogrify = "^2.0.7"
