[tool.poetry]
name = "blog"
version = "0.0.0"
description = "Daniel Himmelstein's Blog"
authors = ["Daniel Himmelstein"]

# https://python-poetry.org/docs/versions/
[tool.poetry.dependencies]
python = "^3.11"
pelican = "^4.9.1"
markdown = "^3.6"
smartypants = "^2.0.1"
jinja2 = "^3.1.4"
typogrify = "^2.0.7"
