name: Blog
on:
- push
- pull_request
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set parameters
      id: params
      shell: bash
      run: |
        DATE_ISO=$(date --utc --iso)
        echo "Setting parameter date_iso=$DATE_ISO"
        echo "date_iso=$DATE_ISO" >> $GITHUB_OUTPUT
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'    
    - name: Install poetry
      run: pip install poetry
    - name: Install dependencies
      run: poetry install --ansi --no-root
    - name: Pelican
      run: poetry run pelican
    - name: Deploy
      if: github.ref == 'refs/heads/main' && github.event_name == 'push' && !github.event.repository.fork
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: output
        publish_branch: gh-pages
        full_commit_message: |
          publish output on ${{ steps.params.outputs.date_iso }}
          
          code version ${{ github.sha }}
          built by <${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}>
