name: Blog
on:
- push
- pull_request
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'    
    - name: Install poetry
      run: pip install poetry
    - name: Install dependencies
      run: poetry install --ansi --no-root
    - name: Pelican
      run: poetry run pelican
    - name: Deploy
      if: github.ref == 'refs/heads/main' && github.event_name == 'push' && !github.event.repository.fork
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: output
        publish_branch: gh-pages
